### ISSUE TITLE
Selected icon color is white.Color cannot be changed

### ISSUE THREAD

**Issue by mukulm24** [thegoal/ISRadioButton#10]
if i change color of icon from storyboard.it does not get reflected.
by default the icon color is White.(which makes the button invisible on white background

**Comment by thegoal** [comment]
indicatorColor is property that changed color of (circle or square on selection), you can set this from storyboard or XIB (ISRadioButton attribute in story board). For text you need to change color for selected state (UIButton attribute).

Note: Make sure you set button type to custom (Default type is system).
