### ISSUE TITLE
get selected other button

### ISSUE THREAD

**Issue by MoatazAbdallh** [thegoal/ISRadioButton#11]
I have outlet for first radio button in my viewController, but when i try to access selected 2nd button through 1stbutton.selectedButton() i got
fatal error: unexpectedly found nil while unwrapping an Optional value
expression produced error: /var/folders/s2/ywrrj42x6j3cm2g_52b8h38w0000gn/T/lldb/562/expr60.swift:1:94: error: 'ISRadioButton' is not a member type of 'ISRadioButton'

any solution?

**Comment by thegoal** [comment]
for other you should get otherButtons from your first (Outlet) button.
