### ISSUE TITLE
Editing selectedButton() func

### ISSUE THREAD

**Issue by MoatazAbdallh** [thegoal/ISRadioButton#12]
i guess that implementation of selectedButton should be edited as current implementation returns only ISRadio button when calling func. on same selected button not return if the selection done on otherButtons.
`public func selectedButton() -> ISRadioButton!{
        if !self.multipleSelectionEnabled {
            if self.selected {
                return self
            }
        }else{
            for isRadioButton in self.otherButtons!  {
                if isRadioButton.selected {
                    return isRadioButton
                }
            }
        }
        return nil
    }`

should be
`if self.selected{
retrun self
}else{
 for isRadioButton in self.otherButtons!  {
                if isRadioButton.selected {
                    return isRadioButton
                }
            }
        }`

**Comment by thegoal** [comment]
ok i will update this after a little testing and thinking on this.
