### ISSUE TITLE
ISradioButton form cocoa pods

### ISSUE THREAD

**Issue by dadixon** [thegoal/ISRadioButton#13]
When I install ISRadioButton from CocoaPods, I can't use all the functions the ISRadioButton has for some reason. For example, I get an error saying that "Value of type ISRadioButton has no member multipleSelectionEnabled". Why is that?

**Comment by thegoal** [comment]
Cocoa Pods are not updated . Please add ISRadioButton.swift in your project and remove cocoa pods .

Sent from my iPhone

On 06-Sep-2016, at 3:48 PM, dadixon <notifications@github.com<mailto:notifications@github.com>> wrote:

When I install ISRadioButton from CocoaPods, I can't use all the functions the ISRadioButton has for some reason. For example, I get an error saying that "Value of type ISRadioButton has no member multipleSelectionEnabled". Why is that?

##
