### ISSUE TITLE
Too slow when Radio Buttons is many like 10+

### ISSUE THREAD

**Issue by karishmapujara** [thegoal/ISRadioButton#17]
Hello
In my app I need 10+ Radio Buttons.
But when I run, my app is freezing & running too slow.

Please help.

**Comment by thegoal** [comment]
I added multiple at screen in demo , but it is running quite well . Please share your scenario that will able me to help .

Sent from my iPhone

On 19-Feb-2017, at 17:38, karishmapujara <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello
In my app I need 10+ Radio Buttons.
But when I run, my app is freezing & running too slow.

Please help.

**Comment by karishmapujara** [comment]
I want to display 15 Radio Buttons with only 1 selected at a time.
So, I implemented them. 
But when I select any radio button, it takes quite a time ( > 1 min.) to select that Radio Button.

**Comment by thegoal** [comment]
Ok let me check i will update you with fix.

Sent from my iPhone

On 19-Feb-2017, at 18:03, karishmapujara <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to display 15 Radio Buttons.
So, I implemented them.
But when I select any radio button, it takes quite a time ( > 1 min.) to select that Radio Button.

**Comment by karishmapujara** [comment]
ok

**Comment by thegoal** [comment]
Fixed .I tested with 20+ Radio Buttons in group.  Please download latest and replace with older one . Best of luck :-)

**Comment by karishmapujara** [comment]
Hello
I received this error 
**fatal error: unexpectedly found nil while unwrapping an Optional value**

at these line:
if ((multipleSelectionEnabled || (oldValue != self.isSelected && self.icon.accessibilityIdentifier == ISRadioButton.kGeneratedIconName && self.iconSelected.accessibilityIdentifier == ISRadioButton.kGeneratedIconName)) && self.animationDuration > 0.0)

**Comment by thegoal** [comment]
Hi , I am unable to reproduce this , a little more explanation will help me to solve this.

**Comment by karishmapujara** [comment]
When i try to selecte any radio button programmatically like
**radiobutton1.isSelected = true**
then i received above error.
Performance issue is solved.

**Comment by thegoal** [comment]
I tried to update as following and it is working fine. Where IBAction is on button click .

     override func viewDidAppear(_ animated: Bool) {
        self.btn1.isSelected = true
     }
    
    @IBAction func btnSelected(_ isRadioButton:ISRadioButton){
        self.btn2.isSelected = true
    }

you can share code snippet if want to discuss . I will glad to help you .

**Comment by karishmapujara** [comment]
radiobutton1.isSelected = true not working in viewDidLoad method
same error
**fatal error: unexpectedly found nil while unwrapping an Optional value**

at these if statement:
**if ((multipleSelectionEnabled || (oldValue != self.isSelected && self.icon.accessibilityIdentifier == ISRadioButton.kGeneratedIconName && self.iconSelected.accessibilityIdentifier == ISRadioButton.kGeneratedIconName)) && self.animationDuration > 0.0)**

if we comment out that whole if statement then it's working fine.
so the problem is in that animation if statement.

**Comment by thegoal** [comment]
Done , Download latest and try.

**Comment by karishmapujara** [comment]
perfect.
