### ISSUE TITLE
Selection style bug

### ISSUE THREAD

**Issue by brod-ie** [thegoal/ISRadioButton#4]
<img width="341" alt="screen shot 2016-06-15 at 13 21 16" src="https://cloud.githubusercontent.com/assets/1520630/16079571/186aaa66-32fc-11e6-9cdc-29d6fade9e8f.png">

As you can see above, the selected radio button is stylised unexpectedly?

**Comment by thegoal** [comment]
Xcode version ? simulater or device ?

**Comment by brod-ie** [comment]
Xcode 7.3.1, simulator (iPhone 6s iOS 9.3)

**Comment by nahouto** [comment]
You have to make the button style Custom (in Interface Builder)

**Comment by brod-ie** [comment]
@nahouto I must of completely missed this step, thank you!
