### ISSUE TITLE
Confused on step three

### ISSUE THREAD

**Issue by jlanders** [thegoal/ISRadioButton#5]
Fairly new with Xcode.  I have everything installed and I am using swift.  I get to step three and am having a difficult time understanding the other buttons part.  Seems this needs to be part of a collection but not show how get the multiple radio buttons attached to a collection.  I will have three sets of collections of radio buttons when done.  Any pointers or examples?  Does this need to be accomplish programmatically or is there a way to group them on the storyboard?

Any assistance is appreciated.

**Comment by thegoal** [comment]
What do you mean by collection ? Do you want single selection from five buttons ? or anything else ?
